### ISSUE TITLE
Colors in 2D plots are not showing up properly.

### ISSUE THREAD

**Issue by amit112amit** [flathub/org.paraview.ParaView#12]
Thank you very much for bundling Paraview as a Flatpak! Sometime back I had opened an issue on Paraview Gitlab if they are interested in offering Paraview as a Flatpak but the devs said that the existing distributions of Paraview work well on a variety of operating systems already so there is no need for Flatpak. Then I had closed the issue. But I am glad that you have successfully done it.

I am facing an issue with 2D plot colors.

Below I have created an arbitrary image data using Sources->Data Object Generator->Hit Apply Button -> Select View to Plot Matrix View. Anywhere 2D plotting is involved the colors are as shown. Do you know if I am missing some Flatpak permissions? The 3D rendering is fine.

![ParaviewWrongColors](https://user-images.githubusercontent.com/8184698/126060314-eadc1fd4-cb04-4f78-8098-1c6b49375a59.png)

**Comment by amit112amit** [comment]
Ok. I found a workaround. It is related to the graphics driver. I ran Paraview using "Launch using Discrete Graphics Card" option of Gnome Desktop environment and now I am getting the colors correct as shown below. I don't know what it means for the bundling of ParaView as a Flatpak.
![ParaviewFlatpakWithNvidia](https://user-images.githubusercontent.com/8184698/126061443-0f075039-26e1-4507-a6a6-3b0f8f6cb6e2.png)

**Comment by kevinsmia1939** [comment]
@amit112amit Thanks for trying out Flatpak. 
I have seen this issue on other software that use ParaView as well. To see if it is Flatpak issue, you will have to install ParaView other ways and see if the issue exist. If it still exist, it's ParaView issue.

Since you solve it, I will close this, feel free to open again if issue persist.

**Comment by amit112amit** [comment]
![OfficialBinary](https://user-images.githubusercontent.com/8184698/126270540-fe5067e5-a92a-46fa-87d0-993340e48744.png)

So as you suggested, I downloaded the official binary from paraview.org and it works fine. Similarly, the ParaView installed from official Fedora repositories also works fine. I feel it is an issue with accessing the graphics drivers inside the flatpak sandbox.

**Comment by kevinsmia1939** [comment]
@amit112amit What hardware do you use.

**Comment by amit112amit** [comment]
![HwInfo](https://user-images.githubusercontent.com/8184698/126314599-6b04282f-1817-42c4-b7f9-5db2b9f7ca9b.png)

@kevinsmia1939 I have a Dell XPS 9550.

**Comment by amit112amit** [comment]
@kevinsmia1939 Do you think including the Mesa runtimes in the Flatpak help?
org.freedesktop.Platform.GL{,32}.default | Mesa drivers (extension)
org.freedesktop.Platform.GL{,32}.mesa-git | Mesa drivers, latest (extension)

**Comment by kevinsmia1939** [comment]
@amit112amit 
ParaView does not need glu, so it is not the issue there. This is a relate to VTK rather than ParaView.

**Comment by amit112amit** [comment]
Ok. I checked the ParaView flatpak on a Ubuntu 20.04 Virtual Machine and the colors are correct there.

**Comment by kevinsmia1939** [comment]
> Ok. I checked the ParaView flatpak on a Ubuntu 20.04 Virtual Machine and the colors are correct there.

I don't really know.

**Comment by amit112amit** [comment]
Yes. I don't have anything helpful to add. I will not bother you again with this issue. Thank you for the flatpak once more.
