### ISSUE TITLE
Add pip support

### ISSUE THREAD

**Issue by jjcasmar** [flathub/org.paraview.ParaView#154]
Paraview allows to do python scripting. However, without pip support, you can only rely on the packages that come prebundled in the flatpak container.

can you add pip support so that user of this flatpak can install other python packages?

**Comment by kevinsmia1939** [comment]
difinitely, I think it is a good idea
just need to change runtime: org.kde.Platform to org.kde.Sdk

**Comment by kevinsmia1939** [comment]
Hi, could you try this build out? 
https://github.com/flathub/org.paraview.ParaView/pull/169

**Comment by kevinsmia1939** [comment]
I believe the issue is fixed. Feel free to reopen if needed.
