### ISSUE TITLE
Add h5py

### ISSUE THREAD

**Issue by jjcasmar** [flathub/org.paraview.ParaView#167]
h5py is a library for supporting HDF5 in python. Would it be possible to add it into the python environment in this flatpak container?

**Comment by kevinsmia1939** [comment]
Hi, could you try this build out? 
https://github.com/flathub/org.paraview.ParaView/pull/169

**Comment by kevinsmia1939** [comment]
I believe the issue is fixed. Feel free to reopen if needed.
