### ISSUE TITLE
Add LAZ support

### ISSUE THREAD

**Issue by romainreignier** [flathub/org.paraview.ParaView#207]
LAZ is a file format for compressed LAS files which are point cloud files.
It seems that the flatpak version of Paraview 5.11.0 does not support LAZ files because I get this error when loading one:
```
[paraview        ]      vtkPDALReader.cxx:115    ERR| vtkPDALReader (0x561545ab1c10): exception: readers.las: Can't read compressed file without LASzip or LAZperf decompression library.
```
It would be nice to add support for it.
Thanks

**Comment by kevinsmia1939** [comment]
I am working on this to enable more plugins.
https://github.com/flathub/org.paraview.ParaView/pull/205

**Comment by kevinsmia1939** [comment]
Please try updating and test again. Let me know if it work.

**Comment by romainreignier** [comment]
Tested, it works.
Thanks a lot!
